name             'monit-graph'
maintainer       'Takuma J Miyake'
maintainer_email 'j.e.miyake@gmail.com'
license          'MIT'
description      'Installs/Configures monit-graph'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.0'
depends          'apache2'
suggests         'monit'
suggests         'nginx'
suggests         'php'
suggests         'php-fpm'
